### ISSUE TITLE
Dump stuff in our own console window

### ISSUE THREAD

**Issue by DanielCauser** [BSiLabs/HttpTracer#1]
https://stackoverflow.com/questions/1094366/how-do-i-write-to-the-visual-studio-output-window-in-my-custom-tool

Let's figure out if it is worth to build an extension for VS to be able to dump information properly colored and formated.

**Comment by ChaseFlorell** [comment]
I just took a run at this and the bits referenced in the SO answer are not compatible with iOS or Android, and therefore won't even compile.

**Comment by DanielCauser** [comment]
Hahaha, so it seems that the libs required for us to do this are not compatible with iOS and Android?

:(

**Comment by dylanberry** [comment]
Closing - out of scope for this library/project.
