### ISSUE TITLE
Format output for Rest Client compatibility

### ISSUE THREAD

**Issue by dylanberry** [BSiLabs/HttpTracer#30]
Format output so calls can easily be copy/pasted into Rest Client: https://marketplace.visualstudio.com/items?itemName=humao.rest-client

**Comment by ChaseFlorell** [comment]
Did you know Rider has a baked in rest client?

**Comment by DanielCauser** [comment]
same format for the vscode extension! :)

**Comment by DanielCauser** [comment]
Hey man!? Still working on this? @dylanberry

**Comment by dylanberry** [comment]
It's done.

**Comment by DanielCauser** [comment]
Yay, will do. I will test it today. I have setup the CI pipeline but we need to setup the CD pipeline.

**Comment by dylanberry** [comment]
This is mostly complete, running through more testing tonight. Should be able to close this with next PR.

**Comment by DanielCauser** [comment]
Addressed in the PR #37
