### ISSUE TITLE
Incompatible with .NETPortable Framework

### ISSUE THREAD

**Issue by saamerm** [BSiLabs/HttpTracer#35]
Hey @DanielCauser, @dylanberry, @ChaseFlorell !
I was excited to add this package into my project when I saw you guys speak about it, but I am getting the following error:

NU1202: Package HttpTracer 1.0.3 is not compatible with portable45-net45+win8+wpa81 (.NETPortable,Version=v4.5,Profile=Profile111). Package HttpTracer 1.0.3 supports:
  - netstandard1.4 (.NETStandard,Version=v1.4)
  - netstandard2.0 (.NETStandard,Version=v2.0)

Is there a way to still add it somehow without changing the Target Framework?

**Comment by DanielCauser** [comment]
Hey @saamerm, indeed we have an open issue #24 to add support for PCL. We parked it for until the community requested it. It might be time to maybe bring it back to life.

**Comment by saamerm** [comment]
Yeah I tried for several hours to convert my app to netstandard2.0 but after spending half a day I landed on an issue I couldn't yet figure how to resolve. Will have to try the upgrade some other day

**Comment by dylanberry** [comment]
@saamerm I'm going to add PCL to our multi-targeting setup. Watch for a new release later today 😄

**Comment by dylanberry** [comment]
@saamerm I tried, it's more painful than I thought to support PCL. LMK if you need a hand converting to netstandard2.0.

**Comment by DanielCauser** [comment]
A lot of compiler directives eh!?

**Comment by dylanberry** [comment]
And conditional references to the HttpClient package too. Ugly. Onward and
upward.

**Comment by saamerm** [comment]
@dylanberry
I appreciate you trying. 
It is painstakingly difficult to convert it to a 2.0, so I will take you up on that offer!
