### ISSUE TITLE
Save request/response and replay

### ISSUE THREAD

**Issue by pug-pelle-p** [BSiLabs/HttpTracer#38]
Hi!
I really like this project, could this be used for testing?
Is there any planned feature for saving requests and responses to disk? And then used that saved data to replay the request, for testing purpose?

**Comment by dylanberry** [comment]
Hi, I'm happy you're finding HttpTracer useful! 

Yes, HttpTracer could certainly be used for testing. There is a sample of saving requests to persistent storage in the sample: https://github.com/BSiLabs/HttpTracer/blob/390cd93ebd2b9b5d48ce84f9dccbdf88fd290ee6/src/HttpTracer.TestApp/ViewModels/MainPageViewModel.cs#L71

There are no plans to replay the saved requests with HttpTracer, but you can use a tool like Rest Client to replay the requests: https://marketplace.visualstudio.com/items?itemName=humao.rest-client

The requests are formatted for Rest Client so this is an ideal option.
