### ISSUE TITLE
[Enhancement] JSON Response appearing indented as JSON 

### ISSUE THREAD

**Issue by saamerm** [BSiLabs/HttpTracer#44]
Sup guys!
I am not sure if this is already possible, but I am not able to figure out if using the package I can make my JSON response appear as indented JSON, so that it's easier to read. Currently I have to 
1. Copy the response I get:
<img width="429" alt="image" src="https://user-images.githubusercontent.com/8262287/75629741-7399ff80-5bb2-11ea-9edd-8fec926a50ff.png">

2. Paste it into VS Code, 
3. Remove the Debug stuff in the beginning of the lines that come after the first line
4. Remove the line breaks and put all of the response in one line
5. Then paste it into https://jsonformatter.curiousconcept.com/ and click "Process" 

Which is a lot of steps, so it would be awesome if there was a way to just change the config so HttpTracer does that!

**Comment by ChaseFlorell** [comment]
you should be able to just copy the http request/response without additional debug info. Does your output not look like this?

```text
INFO:  ==================== HTTP REQUEST: [POST] ==================== 
POST https://xxx.azurewebsites.net/api/entityChangesList
Authorization: Bearer aeiod
client-version: 1.0.0

{"some","value"}

INFO:  ==================== HTTP RESPONSE: [SUCCEEDED: 200 OK] ==================== 

POST https://xxx.azurewebsites.net/api/entityChangesList
StatusCode: 200, ReasonPhrase: 'OK', Version: 1.1, Content: System.Net.Http.StreamContent, Headers:
{
Vary: Accept-Encoding
Server: Microsoft-IIS/10.0
Request-Context: appId=cid-v1:f8caa0cc-5524-4232-86b3-8aad02b0ae0b
Access-Control-Expose-Headers: Request-Context
X-Powered-By: ASP.NET
Date: Sun, 01 Mar 2020 16:53:03 GMT
Content-Length: 122
Content-Type: application/json; charset=utf-8
}

["some","response"]
```

**Comment by saamerm** [comment]
Hey thanks for the quick reply!

It appears like this
<img width="762" alt="image" src="https://user-images.githubusercontent.com/8262287/75629907-3d5d7f80-5bb4-11ea-98ce-e9ec025f8bac.png">

But I was wondering if i can make it look like this: 
<img width="168" alt="image" src="https://user-images.githubusercontent.com/8262287/75629863-cde79000-5bb3-11ea-8c8a-55a445f1f6d0.png">

(Obviously uncollapsed, collapsing was just done to hide the data)

**Comment by ChaseFlorell** [comment]
So, we purposely print it on a single line, but your output still doesn't look quite right. What is your log level?

```csharp
using HttpTracer;
public async Task GetMyData()
{
    var tracer = new HttpTracerHandler();
    tracer.Verbosity = LogLevel.Information; // this line here
    var client = new HttpClient(tracer);
    var result = await client.GetAsync("http://myserviceurl.com");
}
```

**Comment by saamerm** [comment]
It's just set to Default using this line `tracer.Verbosity = HttpTracerHandler.DefaultVerbosity;`

It's separate, but I wasn't able to get access to LogLevel, do I use Splat?

**Comment by ChaseFlorell** [comment]
you don't need splat.  Try updating your "MessageParts" to All and see if it yields better results.

https://github.com/BSiLabs/HttpTracer/blob/e9af456e1f615103c6eab5696eee2d48b07e37aa/src/HttpTracer.Tests/HttpTracerTests.cs#L69

**Comment by saamerm** [comment]
Hmm.. I tried that.
I'm talking about something like this: https://stackoverflow.com/questions/4580397/json-formatter-in-c
Console.WriteLine(JsonConvert.SerializeObject(jsonString, Formatting.Indented));

**Comment by ChaseFlorell** [comment]
That would be a good feature for sure. Probably want to stick it behind an enum configuration value.

Happy to take a pull request 😉

**Comment by saamerm** [comment]
Sure! Any quick tips to what files I would be changing?

**Comment by ChaseFlorell** [comment]
Take a look at the MessageParts and do the same. Values should be

None = 1<<0, //default
IndentRequest = 1<<1,
IndentResponse = 1<<2,
IndentAll = IndentRequest|IndentResponse

**Comment by ChaseFlorell** [comment]
@saamerm I am trying to get this feature through as a part of #51
