### ISSUE TITLE
Is it possible to use this with RestSharp?

### ISSUE THREAD

**Issue by saamerm** [BSiLabs/HttpTracer#48]
I love HTTPTracer and use it for my http clients, but if I'm using RESTSharp, how can I use HttpTracer?

RestSharp using `var client = new RestClient(` instead of `httpclient`

**Comment by ChaseFlorell** [comment]
Thanks for the love @saamerm 
HTTPTracer just leverages `HttpClient`s Chain of Responsibility pattern to apply additional logic around your http requests. A little bit of research shows that RestSharp doesn't actually use the HttpClient, but instead uses `HttpWebRequest`.

I'm not certain how you would inject your own Delegating Handler into their framework `¯\_(ツ)_/¯ `

https://github.com/restsharp/RestSharp/issues/1406

**Comment by dylanberry** [comment]
@saamerm While the restsharp team is working on migrating to HttpClient, I would recommend https://github.com/reactiveui/refit over RestClient if you have the choice.

**Comment by ChaseFlorell** [comment]
I'm going to close this issue as I believe HttpTracer will not work to support HttpWebRequest unless there is a community contribution
